SELECT
CUST_NUM
FROM dbo.CUSTOMERS
WHERE CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS);

SELECT 
o.ORDER_NUM, 
c.CUST_NUM
FROM dbo.ORDERS o
JOIN dbo.CUSTOMERS c ON o.CUST = c.CUST_NUM
WHERE c.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS);

SELECT TOP 
1 o.ORDER_NUM,
o.ORDER_DATE,
c.CUST_NUM
FROM dbo.ORDERS o
JOIN dbo.CUSTOMERS c ON o.CUST = c.CUST_NUM
WHERE c.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
ORDER BY o.ORDER_DATE DESC;