-- Завдання 1
SELECT MFR, PRODUCT
FROM (
    SELECT MFR, PRODUCT, 
           ROW_NUMBER() OVER (PARTITION BY MFR, PRODUCT ORDER BY MFR) AS RowNum
    FROM [dbo].[ORDERS]
) AS RankedOrders
WHERE RowNum = 1;

-- Завдання 2
SELECT MFR, PRODUCT
FROM [dbo].[ORDERS]
GROUP BY MFR, PRODUCT
HAVING COUNT(*) > 1;

-- Завдання 3
SELECT TITLE, EMPL_NUM, HIRE_DATE, WorkYears
FROM (
    SELECT TITLE, EMPL_NUM, HIRE_DATE,
           DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS WorkYears,
           DENSE_RANK() OVER (PARTITION BY TITLE ORDER BY DATEDIFF(YEAR, HIRE_DATE, GETDATE()) DESC) AS Rank
    FROM [dbo].[SALESREPS]
) AS RankedReps
WHERE Rank = 1;
