



SELECT OFFICE, CITY, MGR
FROM dbo.OFFICES
WHERE REGION = 'Eastern' AND TARGET <= 350000.00;






SELECT *
FROM dbo.ORDERS
WHERE ORDER_DATE NOT BETWEEN '2008-01-01' AND '2008-12-31'
  AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%');






  SELECT MFR, COUNT(DISTINCT ORDER_NUM) AS TotalOrders, SUM(AMOUNT) AS TotalAmount
FROM dbo.ORDERS
WHERE ORDER_DATE NOT BETWEEN '2008-01-01' AND '2008-12-31'
  AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR
ORDER BY TotalAmount ASC;




SELECT TOP 1 WITH TIES MFR, SUM(AMOUNT) AS TotalAmount
FROM dbo.ORDERS
WHERE ORDER_DATE NOT BETWEEN '2008-01-01' AND '2008-12-31'
  AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR
ORDER BY TotalAmount DESC;





SELECT TOP 1 WITH TIES [REP_OFFICE], COUNT([EMPL_NUM]) AS EmployeeCount 
FROM dbo.SALESREPS 
WHERE [TITLE]= 'Sales Rep' AND Age IN (29, 45, 48) 
GROUP BY [REP_OFFICE]
ORDER BY EmployeeCount DESC;