SELECT DISTINCT O.MFR
FROM dbo.CUSTOMERS C
INNER JOIN dbo.ORDERS O
    ON C.CUST_NUM = O.CUST
WHERE O.ORDER_DATE >= '2008-01-01' 
  AND O.ORDER_DATE < '2009-01-01'
  AND C.COMPANY LIKE '%CORP%';

  SELECT C.CUST_NUM, MONTH(O.ORDER_DATE) AS ORDER_MONTH, COUNT(DISTINCT O.ORDER_NUM) AS UNIQUE_ORDERS
FROM dbo.CUSTOMERS C
LEFT OUTER JOIN dbo.ORDERS O
    ON C.CUST_NUM = O.CUST
   AND O.ORDER_DATE >= '2008-01-01' 
   AND O.ORDER_DATE < '2009-01-01'
   AND C.COMPANY LIKE '%CORP%'
GROUP BY C.CUST_NUM, MONTH(O.ORDER_DATE)
ORDER BY UNIQUE_ORDERS DESC;

SELECT C.CUST_NUM, UPPER(C.COMPANY) AS COMPANY_NAME, P.[DESCRIPTION]
FROM dbo.CUSTOMERS C
LEFT OUTER JOIN dbo.ORDERS O
    ON C.CUST_NUM = O.CUST
   AND O.ORDER_DATE >= '2008-01-01' 
   AND O.ORDER_DATE < '2009-01-01'
   AND C.COMPANY LIKE '%CORP%'
LEFT OUTER JOIN dbo.PRODUCTS P
    ON O.PRODUCT = P.PRODUCT_ID
WHERE O.ORDER_DATE IS NOT NULL OR P.[DESCRIPTION] IS NOT NULL;