SELECT DISTINCT O.MFR
FROM dbo.ORDERS O
INNER JOIN dbo.CUSTOMERS C 
    ON O.CUST = C.CUST_NUM
WHERE O.ORDER_DATE BETWEEN '20080101' AND '20081231'
  AND C.COMPANY LIKE '%CORP%';

  SELECT 
    C.CUST_NUM,
    MONTH(O.ORDER_DATE) AS ORDER_MONTH,
    COUNT(DISTINCT O.ORDER_NUM) AS UNIQUE_ORDERS
FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O 
    ON C.CUST_NUM = O.CUST
    AND O.ORDER_DATE BETWEEN '20080101' AND '20081231'
WHERE C.COMPANY LIKE '%CORP%'
GROUP BY C.CUST_NUM, MONTH(O.ORDER_DATE)
ORDER BY UNIQUE_ORDERS DESC;


SELECT DISTINCT 
    C.CUST_NUM,
    UPPER(C.COMPANY) AS COMPANY_NAME,
    P.DESCRIPTION
FROM dbo.CUSTOMERS C
LEFT JOIN dbo.ORDERS O ON C.CUST_NUM = O.CUST
AND O.ORDER_DATE BETWEEN '20080101' AND '20081231'
LEFT JOIN dbo.PRODUCTS P ON O.MFR = p.MFR_ID AND O.PRODUCT = P.PRODUCT_ID
WHERE C.COMPANY LIKE '%CORP%';