SELECT DISTINCT MFR
FROM [dbo].[ORDERS]
WHERE AMOUNT % 2 = 0
  AND QTY % 2 = 1
ORDER BY MFR;


SELECT 
    MFR_ID,
    ROUND(SUM(QTY_ON_HAND * PRICE), 2) AS total_value,
    ROUND(AVG(PRICE), 2) AS average_price
FROM [dbo].[PRODUCTS]
GROUP BY MFR_ID
ORDER BY MFR_ID;


SELECT 
    EMPL_NUM,
    NAME,
    ROUND(ABS(SALES - QUOTA), 2) AS abs_difference,
    DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS years_at_hire
FROM [dbo].[SALESREPS]
WHERE ABS(QUOTA - SALES) = (
    SELECT MAX(ABS(QUOTA - SALES))
    FROM [dbo].[SALESREPS]
)
ORDER BY EMPL_NUM;