SELECT 
MFR_ID, 
PRODUCT_ID, 
DESCRIPTION, 
LEN(DESCRIPTION) AS DescriptionLength
FROM 
[dbo].[PRODUCTS]
WHERE 
LEN(DESCRIPTION) = (
SELECT MAX(LEN(DESCRIPTION)) 
FROM [dbo].[PRODUCTS]);

SELECT DISTINCT
CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION])) AS ConcatenatedText,
LEN(CONCAT_WS(' ', RTRIM(MFR_ID), RTRIM(PRODUCT_ID), RTRIM([DESCRIPTION]))) AS TextLength
FROM 
[dbo].[PRODUCTS]
WHERE 
PRODUCT_ID NOT LIKE '%[^0-9]%'  
ORDER BY 
TextLength DESC;

SELECT 
[CUST_NUM], 
LEFT([CUST_NUM], 2) + REPLICATE('*', LEN([CUST_NUM]) - 4) + RIGHT([CUST_NUM], 2) AS MaskedCustomerName,
CREDIT_LIMIT
FROM 
[dbo].[CUSTOMERS]
WHERE 
CREDIT_LIMIT = (
SELECT MIN(CREDIT_LIMIT) 
FROM [dbo].[CUSTOMERS]);
